api_version = "2025-10"

[[extensions]]
name = "t:name"
handle = "bag-offer-discount"
type = "function"
uid = "019f3840-3b45-71bc-90b9-6452a0514297"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
